const express=require('express')
const app=express()
const cors=require('cors')
const bodyParser=require('body-parser')
const {userDetails,customer_details,marked}=require('./controller/Userdata')
const login=require('./controller/login')
app.use(express.json())
app.use(bodyParser.urlencoded({extended:true}))
app.use(cors())
app.get('/',(req,res)=>{
    res.send('Hello what can i Help for U...')
})  
app.post('/book',customer_details)
app.post('/admin',login)
app.post('/details',userDetails)
app.post('/marked',marked)
app.listen(5000,()=>console.log('port is listen in 5000'))
